name: Release PR builder

on:
  push:
#    branches:
#      - master
#    types:
#      - opened

jobs:
  release-pr-builder:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: "PIP Cache"
        uses: actions/cache@v2
        env:
          cache-name: cache-pip-modules
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-gha-${{ env.cache-name }}-${{ hashFiles('.github/scripts/requirements.txt') }}
          restore-keys: |
            - ${{ runner.os }}-gha-${{ env.cache-name }}-${{ hashFiles('.github/scripts/requirements.txt') }}
            - ${{ runner.os }}-gha-${{ env.cache-name }}-
      - name: "Install dependencies"
        run: pip install -r .github/scripts/requirements.txt
      - name: Run
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          python3 .github/scripts/gh_api.py
